# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

pool:
  vmImage: 'ubuntu-latest'

variables:
  elasticImageName: 'cookpad/elasticsearch-fast-cosine-similarity'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    options: '--no-daemon'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.12'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'bundlePlugin'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'build/distributions/**/?(*.zip)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: fast-cosine-similarity-plugin.zip
- task: Docker@1
  inputs:
    command: Build an image
    Dockerfile: '**/Dockerfile'
    imageName: '$(elasticImageName):$(Build.BuildNumber)'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS DevelopmentPowerUser'
    regionName: 'eu-west-1'
    imageSource: imagename
    sourceImageName: '$(elasticImageName)'
    sourceImageTag: '$(Build.BuildNumber)'
    pushTag: '$(Build.BuildNumber)'
    repositoryName: '$(elasticImageName)'
    autoCreateRepository: true
    logRequest: true
    logResponse: true
